# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - cisoa

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ciso2025.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_15a455f556fb45ef9f9c9cef6873e3b9 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9d62b262f32f4f5295f1a08cc6fc7ab4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ciso2025.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_15a455f556fb45ef9f9c9cef6873e3b9 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cisoa'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a97953645c0d44e5966b2cdd3a72c98a }}
        images: 'ciso2025.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_15a455f556fb45ef9f9c9cef6873e3b9 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}'